### PR TITLE
iOrnament fullsize

### PR DESCRIPTION
**Pull request by montaga**
This PR adopts iOrnament to fill the entire screen.
So far, the change only becomes visible if `iornament/app.html` is loaded directly and not through `iornament/index.html` through `viewer/cindy-viewer.js`.

Since @richter-gebert is the creator of iOrnament, he also should have a final look
on this before we merge this.

### CODE REVIEW

**Comment by porst17** [comment]
Thank you for the PR! I just tested it on a 4K screen and it works quite well so far.

However, there a couple of smaller issues with this PR:

- [ ] if you move the mouse fast enough, the individual dots are not connected anymore. This is something that happens frequently on touch screens (see image below)
- [ ] it breaks support for Mozilla Firefox (only tested with 63.0.1 on macOS).
- [ ] currently, we don't have a proper way to deal with different versions of the `Cindy.js` in our repo. The applets that rely on the `common/js/Cindy.js` library don't work with the `common-music/js/Cindy.js` library and vice versa (AFAIK). If we add yet another (unversioned) copy of `Cindy.js`, the situation becomes even worse. I would really like to avoid that and have one version of the library that fits all.

**Comment by porst17** [comment]
grafik

**Comment by porst17** [comment]
More issues:

- [ ]  Stroke width of circles around the color selectors is not properly scaled in Chrome (when I make the window smaller)
- [ ] The color selectors disappear depending on the resolution (happens in both, Firefox and Chrome)

grafik

**Comment by richter-gebert** [comment]
Hi everybody

very briefly (heavily multitasking here)

> On 5. Nov 2018, at 14:20, Christian Stussak <notifications@github.com> wrote:
> 
> Thank you for the PR! I just tested it on a 4K screen and it works quite well so far.
> 
> However, there a couple of smaller issues with this PR:
> 
>  if you move the mouse fast enough, the individual dots are not connected anymore. This is something that happens frequently on touch screens (see image below)

I have to go into the rendering code to work on that (should be rewritten anyways :-) ).
I fear I will not find time to do this before End of Nov. But the should be early enough.

>  it breaks support for Mozilla Firefox (only tested with 63.0.1 on macOS).

brrrrr….Aaron, can you help?

>  currently, we don't have a proper way to deal with different versions of the Cindy.js in our repo. The applets that rely on the common/js/Cindy.js library don't work with the common-music/js/Cindy.js library and vice versa (AFAIK). If we add yet another (unversioned) copy of Cindy.js, the situation becomes even worse. I would really like to avoid that and have one version of the library that fits all.

I’m not sure if we can promise this. But we can try.

So far for the moment

Jürgen

**Comment by montaga** [comment]
My last commit should solve several of the issues related to rescaling/firefox/colors disappearing.

**Comment by porst17** [comment]
Thank you both. I'll check it tomorrow morning. (Also heavily multitasking here ...)

**Comment by richter-gebert** [comment]
One question: are we preparing for single touch or multi touch?


--------------------------------------
Prof. Jürgen Richter-Gebert
Geometrie und Visualisierung
Zentrum Mathematik --- TU München
Boltzmannstr. 3
85747 Garching bei München
Tel: 089/28918354, Sekr: 089/28918359
e-mail: richter@ma.tum.de

**Comment by porst17** [comment]
@richter-gebert The station (and the kiosk browser) will allow for multi touch. But IIRC, CindyJS does not support multi touch, right? For the Ornament drawing, it would be awesome to have multi touch, of course.

But right now, I think it is more important to have a version that just works on the high res screen.

We can update the app any time later to multi touch. We will have remote access to the exhibition PCs.

**Comment by elondaits** [comment]
Already included in merged #3

**Pull request closed without merging**
